### ISSUE TITLE
'MergeDict' object does not support item assignment

### ISSUE THREAD

**Issue by nordbit** [kunitoki/django-formaldehyde#1]
```
  File "/srv/python3/lib/python3.4/site-packages/formaldehyde/whitespace.py", line 30, in strip_whitespace_from_data
    data[key] = value
TypeError: 'MergeDict' object does not support item assignment
```

Django == 1.8.2, Python 3.4

**Comment by kunitoki** [comment]
mmmh something must have changed in the django internals. thanx for reporting.

**Comment by kunitoki** [comment]
i tried to blindly fix this... check 5420866b5835474754c7276b5b9db5680221f3be if it's working for you.

**Comment by nordbit** [comment]
Error occurs when i click 'Agenda" tab in menu
I paste full log:

```
[15/Jun/2015 21:30:24]"GET /nublas/association/f91a346405e640a3963c9ebedbfd7d74/contacts/ HTTP/1.1" 200 18017
[15/Jun/2015 21:30:29]"GET /nublas/association/f91a346405e640a3963c9ebedbfd7d74/agenda/ HTTP/1.1" 200 15452
[15/Jun/2015 21:30:29]"GET /nublas/association/f91a346405e640a3963c9ebedbfd7d74/events/style.css HTTP/1.1" 200 335
ERROR Internal Server Error: /nublas/association/f91a346405e640a3963c9ebedbfd7d74/events/
Traceback (most recent call last):
  File "/srv/python3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/srv/python3/myproject/nublas/ui/views/agenda.py", line 149, in dispatch
    form = ListEventByDateForm(request.REQUEST)
  File "/srv/python3/myproject/nublas/ui/forms.py", line 88, in __init__
    self._update_widgets_error_state()
  File "/srv/python3/myproject/nublas/ui/forms.py", line 58, in _update_widgets_error_state
    if self.errors:
  File "/srv/python3/lib/python3.4/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/srv/python3/myproject/nublas/ui/forms.py", line 98, in full_clean
    self.strip_whitespace_from_data()
  File "/srv/python3/lib/python3.4/site-packages/formaldehyde/whitespace.py", line 30, in strip_whitespace_from_data
    data.update({ key: value })
AttributeError: 'MergeDict' object has no attribute 'update'
Internal Server Error: /nublas/association/f91a346405e640a3963c9ebedbfd7d74/events/
Traceback (most recent call last):
  File "/srv/python3/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/python3/lib/python3.4/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/srv/python3/myproject/nublas/ui/views/agenda.py", line 149, in dispatch
    form = ListEventByDateForm(request.REQUEST)
  File "/srv/python3/myproject/nublas/ui/forms.py", line 88, in __init__
    self._update_widgets_error_state()
  File "/srv/python3/myproject/nublas/ui/forms.py", line 58, in _update_widgets_error_state
    if self.errors:
  File "/srv/python3/lib/python3.4/site-packages/django/forms/forms.py", line 176, in errors
    self.full_clean()
  File "/srv/python3/myproject/nublas/ui/forms.py", line 98, in full_clean
    self.strip_whitespace_from_data()
  File "/srv/python3/lib/python3.4/site-packages/formaldehyde/whitespace.py", line 30, in strip_whitespace_from_data
    data.update({ key: value })
AttributeError: 'MergeDict' object has no attribute 'update'
[15/Jun/2015 21:30:29]"GET /nublas/association/f91a346405e640a3963c9ebedbfd7d74/events/?start=2015-06-01&end=2015-07-13&_=1434396687027 HTTP/1.1" 500 24997
```

**Comment by nordbit** [comment]
4009a9d98ac1b4da69af876e84a745f3aa5e076c
